apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-wave-man-config
  namespace: web
  labels:
    app: demo-man
    svc: wave-man
data:
  small.json: |
    {
      "step_width": 16,
      "height": 200,
      "color": "{{.color}}",
      "rounded": 8,
      "steps": 25,
      "gap": 8,
      "mode": "rounded_avg",
      "align": "center",
      "sr": 48000,
      "mono": true,
      "scale": 1,
      "dpi": 600,
      "preserveAspectRatio": "none" 
    }
  full.json: |
    {
      "step_width": 20,
      "height": 200,
      "color": "{{.color}}",
      "rounded": 10,
      "steps": 50,
      "gap": 10,
      "mode": "rounded_avg",
      "align": "center",
      "sr": 48000,
      "mono": true,
      "scale": 1,
      "dpi": 600,
      "preserveAspectRatio": "none"
    }
