apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-waveman-config
  namespace: web
  labels:
    app: demo-man
    svc: waveman
data:
  small.json: |
    {
      "step_width": 16,
      "height": 200,
      "color": "{{.color}}",
      "rounded": 8,
      "steps": 25,
      "gap": 8,
    }
  full.json: |
    {
      "step_width": 20,
      "height": 200,
      "color": "{{.color}}",
      "rounded": 10,
      "steps": 50,
      "gap": 10,
    }
