apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: web
  labels:
    app: demo-man
    svc: api
spec:
  selector:
    matchLabels:
      app: demo-man
      svc: api
  template:
    metadata:
      labels:
        app: demo-man
        svc: api
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: github
      - name: gitlab
      containers:
      - name: api
        image: registry.git.rwth-aachen.de/occloxium-webdev/demo-zoomoid-de/api:v1.14
        env:
        - name: MONGOURL
          value: "mongodb://demo-mongodb:27017"
        - name: DB
          value: "demo"
        - name: WAVE_ENDPOINT
          value: http://demo-waveman:8080/
        - name: API_ENDPOINT
          value: https://demo.zoomoid.de/api/v1/demo
        - name: PORT
          value: "8080"
        - name: TOKEN 
          valueFrom:
            secretKeyRef:
              name: demo-zoomoid-de-api-token-secret
              key: token
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-waveman
  namespace: web
spec:
  selector:
    matchLabels:
      app: demo-man
      svc: waveman
  template:
    metadata:
      labels:
        app: demo-man
        svc: waveman
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: github
      - name: gitlab
      containers:
      - name: waveman
        image: registry.git.rwth-aachen.de/occloxium-webdev/demo-zoomoid-de/waveman:v1.14
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: audio-volume
          mountPath: "/app/files"
        - name: waveman-config
          mountPath: /app/config
        resources:
          limits:
            memory: "1Gi"
          requests:
            cpu: "500m"
      volumes:
      - name: audio-volume
        persistentVolumeClaim:
          claimName: demo-waveman-pvc
      - name: waveman-config
        configMap:
          name: demo-waveman-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-client
  namespace: web
  labels:
    svc: client
    app: demo-man
spec:
  selector:
    matchLabels:
      app: demo-man
      svc: client
  template:
    metadata:
      labels:
        app: demo-man
        svc: client
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: github
      - name: gitlab
      containers:
      - name: client
        image: registry.git.rwth-aachen.de/occloxium-webdev/demo-zoomoid-de/client:v1.14
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-watchdog
  namespace: web
  labels:
    app: demo-man
    svc: watchdog
spec:
  selector:
    matchLabels:
      app: demo-man
      svc: watchdog
  template:
    metadata:
      labels:
        app: demo-man
        svc: watchdog
    spec:
      imagePullSecrets:
      - name: github
      - name: gitlab
      containers:
      - name: watchdog
        image: registry.git.rwth-aachen.de/occloxium-webdev/demo-zoomoid-de/watchdog:v1.14
        env:
        - name: VOLUME
          value: "/app/files"
        - name: PUBLIC_PATH
          value: '{"prefix": "https", "hostname": "files.zoomoid.de", "dir": ""}'
        - name: API_ENDPOINT
          value: http://demo-api:8080/api/v1/demo
        - name: TOKEN 
          valueFrom:
            secretKeyRef:
              name: demo-zoomoid-de-api-token-secret
              key: token
        volumeMounts:
        - mountPath: "/app/files"
          name: audio-volume
      volumes:
      - name: audio-volume
        persistentVolumeClaim:
          readOnly: true
          claimName: demo-watchdog-pvc
      restartPolicy: Always