apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: web
  labels:
    app: demo-man
    svc: api
spec:
  selector:
    matchLabels:
      app: demo-man
      svc: api
  template:
    metadata:
      labels:
        app: demo-man
        svc: api
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: github
      - name: gitlab
      containers:
      - name: api
        image: registry.git.rwth-aachen.de/occloxium-webdev/demo-zoomoid-de/api:v1.11
        env:
        - name: MONGOURL
          value: "mongodb://demo-mongodb:27017"
        - name: DB
          value: "demo"
        - name: WAVE_ENDPOINT
          value: http://demo-wave-man:8080/wavify
        - name: API_ENDPOINT
          value: https://demo.zoomoid.de/api/v1/demo
        - name: PORT
          value: "8080"
        - name: TOKEN 
          valueFrom:
            secretKeyRef:
              name: demo-zoomoid-de-api-token-secret
              key: token
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-wave-man
  namespace: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-man
      svc: wave-man
  template:
    metadata:
      labels:
        app: demo-man
        svc: wave-man
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: github
      - name: gitlab
      containers:
      - name: wave-man
        image: docker.pkg.github.com/occloxium/wave-man/wave-man:2.19.4
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: wave-man-volume
          mountPath: "/app/tmp"
        - name: wave-man-config
          mountPath: /app/config
        resources:
          limits:
            memory: "2Gi"
          requests:
            cpu: "1000m"
      volumes:
      - name: wave-man-volume
        persistentVolumeClaim:
          claimName: demo-wave-man-pvc
      - name: wave-man-config
        configMap:
          name: demo-wave-man-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-client
  namespace: web
  labels:
    svc: client
    app: demo-man
spec:
  selector:
    matchLabels:
      app: demo-man
      svc: client
  template:
    metadata:
      labels:
        svc: client
        app: demo-man
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: github
      - name: gitlab
      containers:
      - name: client
        image: registry.git.rwth-aachen.de/occloxium-webdev/demo-zoomoid-de/client:v1.11
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-watchdog
  namespace: web
  labels:
    app: demo-man
    svc: watchdog
spec:
  selector:
    matchLabels:
      app: demo-man
      svc: watchdog
  template:
    metadata:
      labels:
        app: demo-man
        svc: watchdog
    spec:
      imagePullSecrets:
      - name: github
      - name: gitlab
      containers:
      - name: watchdog
        image: registry.git.rwth-aachen.de/occloxium-webdev/demo-zoomoid-de/watchdog:v1.11
        env:
        - name: VOLUME
          value: "/app/files"
        - name: PUBLIC_PATH
          value: '{"prefix": "https", "hostname": "files.zoomoid.de", "dir": ""}'
        - name: API_ENDPOINT
          value: http://demo-api:8080/api/v1/demo # use service name instead of global public endpoint
        - name: TOKEN 
          valueFrom:
            secretKeyRef:
              name: demo-zoomoid-de-api-token-secret
              key: token
        volumeMounts:
        - mountPath: "/app/files"
          name: audio-volume
      volumes:
      - name: audio-volume
        persistentVolumeClaim:
          claimName: demo-audio-pvc
      restartPolicy: Always