apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-zoomoid-de
  namespace: web
spec:
  selector:
    matchLabels:
      app: demo-zoomoid-de
  template:
    metadata:
      labels:
        app: demo-zoomoid-de
    spec:
      containers:
      - name: api
        image: docker.pkg.github.com/occloxium/demo-man/api:1.0.0
        env:
          - name: MONGOURL
            value: "mongodb://demo-mondodb:27017"
          - name: DB
            value: "demo"
          - name: PORT
            value: "8080"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
      - name: client
        image: docker.pkg.github.com/occloxium/demo-man/client:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
      - name: watchdog
        image: docker.pkg.github.com/occloxium/demo-man/watchdog:1.0.0
        env:
          - name: VOLUME
            value: "/app/files"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: "/app/files"
            name: audio-volume
      - name: pusher
        image: registry.git.rwth-aachen.de/occloxium-webdev/demo.zoomoid.de/pusher:2.0.0
        env:
          - name: VOLUME
            value: "/pusher/files"
          - name: PORT
            value: "3000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: "/pusher/files"
            name: audio-volume
      volumes:
      - name: audio-volume
        persistentVolumeClaim:
          claimName: demo-audio-pvc
      restartPolicy: Always
      imagePullSecrets:
        - gitlab
      nodeSelector:
        view: left # schedule to left-wing as volume for watchdog persists only there

