apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: web
  labels:
    app: demo-api
spec:
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: github
      containers:
      - name: api
        image: docker.pkg.github.com/occloxium/demo-man/api:1.1.2
        env:
          - name: MONGOURL
            value: "mongodb://demo-mondodb:27017"
          - name: DB
            value: "demo"
          - name: PORT
            value: "80"
          - name: TOKEN 
            valueFrom:
              secretKeyRef:
                name: demo-zoomoid-de-api-token-secret
                key: token
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-client
  namespace: web
  labels:
    app: demo-client
spec:
  selector:
    matchLabels:
      app: demo-client
  template:
    metadata:
      labels:
        app: demo-client
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: github
      containers:
      - name: client
        image: docker.pkg.github.com/occloxium/demo-man/client:1.1.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-watchdog
  namespace: web
  labels:
    app: demo-watchdog
spec:
  selector:
    matchLabels:
      app: demo-watchdog
  template:
    metadata:
      labels:
        app: demo-watchdog
    spec:
      imagePullSecrets:
        - name: github
      containers:
      - name: watchdog
        image: docker.pkg.github.com/occloxium/demo-man/watchdog:1.1.2
        env:
          - name: VOLUME
            value: "/app/files"
          - name: PUBLIC_PATH
            value: '{"prefix": "https", "hostname": "files.zoomoid.de", "dir": ""}'
          - name: API_ENDPOINT
            value: http://demo-api/api/v1/demo
          - name: TOKEN 
            valueFrom:
              secretKeyRef:
                name: demo-zoomoid-de-api-token-secret
                key: token
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: "/app/files"
            name: audio-volume
      volumes:
      - name: audio-volume
        persistentVolumeClaim:
          claimName: demo-audio-pvc
      restartPolicy: Always
