apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-api
  namespace: web
spec:
  selector:
    matchLabels:
      app: demo-api
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: github
      containers:
      - name: api
        image: docker.pkg.github.com/occloxium/demo-man/api:1.4.2
        env:
        - name: MONGOURL
          value: "mongodb://demo-mongodb:27017"
        - name: DB
          value: "demo"
        - name: WAVE_ENDPOINT
          value: http://demo-wave-man/wavify
        - name: API_ENDPOINT
          value: https://demo.zoomoid.de/api/v1/demo
        - name: PORT
          value: "8080"
        - name: TOKEN 
          valueFrom:
            secretKeyRef:
              name: demo-zoomoid-de-api-token-secret
              key: token
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
          failureThreshold: 6
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-wave-man
  namespace: web
spec:
  selector:
    matchLabels:
      app: demo-wave-man
  template:
    metadata:
      labels:
        app: demo-wave-man
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: github
      containers:
      - name: wave-man
        image: docker.pkg.github.com/occloxium/wave-man/wave-man-server:2.9
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-client
  namespace: web
spec:
  selector:
    matchLabels:
      app: demo-client
  template:
    metadata:
      labels:
        app: demo-client
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: github
      containers:
      - name: client
        image: docker.pkg.github.com/occloxium/demo-man/client:1.4.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-watchdog
  namespace: web
  labels:
    app: demo-watchdog
spec:
  selector:
    matchLabels:
      app: demo-watchdog
  template:
    metadata:
      labels:
        app: demo-watchdog
    spec:
      imagePullSecrets:
      - name: github
      containers:
      - name: watchdog
        image: docker.pkg.github.com/occloxium/demo-man/watchdog:1.4.1
        env:
        - name: VOLUME
          value: "/app/files"
        - name: PUBLIC_PATH
          value: '{"prefix": "https", "hostname": "files.zoomoid.de", "dir": ""}'
        - name: API_ENDPOINT
          value: http://demo-api:8080/api/v1/demo # use service name instead of global public endpoint
        - name: TOKEN 
          valueFrom:
            secretKeyRef:
              name: demo-zoomoid-de-api-token-secret
              key: token
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - mountPath: "/app/files"
          name: audio-volume
      volumes:
      - name: audio-volume
        persistentVolumeClaim:
          claimName: demo-audio-pvc
      restartPolicy: Always
