apiVersion: v1
kind: Service
metadata:
  name: demo-api
  namespace: web
  labels:
    app: demo-man
    svc: api
spec:
  selector:
    app: demo-man
    svc: api
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-client
  namespace: web
  labels:
    app: demo-man
    svc: client
spec:
  selector:
    app: demo-man
    svc: client
  ports:
  - port: 8081
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: demo-waveman
  namespace: web
  labels:
    app: demo-man
    svc: waveman
spec:
  selector:
    app: demo-man
    svc: waveman
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: web
  name: demo-mongodb
  labels:
    app: demo-man
    svc: mongodb
spec:
  selector:
    app: demo-man
    svc: mongodb
  ports:
  - port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: demo-fileserver
spec:
  selector:
    app: demo-man
    svc: fileserver
  ports:
  - port: 80
    targetPort: 80