apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-mongodb-pv
  namespace: web
  labels:
    app: demo-man
    svc: mongodb
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s/demo-zoomoid-de/mongodb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-mongodb-pvc
  namespace: web
  labels:
    app: demo-man
    svc: mongodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
    limits:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-audio-pv
  namespace: web
  labels:
    app: demo-man
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s/demo-man"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-audio-pvc
  namespace: web
  labels:
    app: demo-man
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-wave-man-pv
  namespace: web
  labels:
    app: demo-man
    svc: wave-man
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s/demo-wave-man"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-wave-man-pvc
  namespace: web
  labels:
    app: demo-man
    svc: wave-man
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
    limits:
      storage: 1Gi