apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-mongodb-pv
  namespace: web
  labels:
    app: demo-man
    svc: mongodb
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s/demo-zoomoid-de/mongodb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-mongodb-pvc
  namespace: web
  labels:
    app: demo-man
    svc: mongodb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
    limits:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-audio-pv
  namespace: web
  labels:
    app: demo-man
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s/demo-man"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-watchdog-pvc
  namespace: web
  labels:
    app: demo-man
    svc: watchdog
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-waveman-pvc
  namespace: web
  labels:
    app: demo-man
    svc: waveman
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 10Gi