# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: demo-mongodb-pv
#   namespace: web
#   labels:
#     app: demo-mongodb
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 4Gi
#   accessModes:
#     - ReadWriteMany
#   hostPath:
#     path: "/mnt/k8s/demo-zoomoid-de/mongodb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-mongodb-pvc
  namespace: web
  labels:
    app: demo-mongodb
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
    limits:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-audio-pv
  namespace: web
  labels:
    app: demo-zoomoid-de
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/k8s/demo-man"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-audio-pvc
  namespace: web
  labels:
    app: demo-zoomoid-de
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 10Gi