version: "3"

services:
  client:
    image: client:latest
    container_name: demo-client
    restart: on-failure
    networks: 
    - frontend
    ports: 
    - "8081:80"

  api:
    image: api:latest
    container_name: demo-api
    restart: on-failure
    environment: 
      MONGOURL: mongodb://demo-mongodb:27017
      DB: demo
      TOKEN: demotoken
    networks:
    - backend
    - frontend
    ports: 
    - "8080:8080"

  watchdog:
    image: watchdog:latest
    container_name: demo-watchdog
    restart: on-failure
    ports:
    - "8082:8080"
    environment: 
      VOLUME: /app/files
      PUBLIC_PATH: '{"prefix": "https", "hostname": "files.zoomoid.de", "dir": ""}'
      TOKEN: demotoken
      API_ENDPOINT: http://demo-api
      DRY_RUN: true
    volumes:
    - ./files:/app/files
    networks:
    - backend

  db:
    image: mongo:4.2.5
    container_name: demo-mongodb
    restart: on-failure
    volumes:
    - db-data:/data/db
    environment: 
      MONGO_INITDB_DATABASE: demo
    networks:
    - backend
    ports:
    - "27017:27017"

networks:
  frontend:
  backend:

volumes:
  db-data: