version: "3"

services:
  client:
    build: ../client
    container_name: demo-client
    restart: on-failure
    networks: 
    - frontend
    ports: 
    - "8081:80"

  api:
    build: ../api
    container_name: demo-api
    restart: on-failure
    depends_on: 
    - db
    environment: 
      PORT: "8080"
      MONGOURL: mongodb://demo-mongodb:27017
      WAVE_ENDPOINT: 'http://demo-wave-man:5000/wavify'
      API_ENDPOINT: 'http://demo-api:8080/api/v1/demo'
      DB: demo
      TOKEN: demotoken
    networks:
    - backend
    - frontend
    ports: 
    - "8080:8080"

  watchdog:
    build: ../watchdog
    container_name: demo-watchdog
    restart: on-failure
    ports:
    - "8082:8080"
    environment: 
      VOLUME: /app/files
      PUBLIC_PATH: '{"prefix": "https", "hostname": "files.zoomoid.de", "dir": ""}'
      TOKEN: demotoken
      API_ENDPOINT: 'http://demo-api:8080/api/v1/demo'
    volumes:
    - ./files:/app/files
    networks:
    - backend

  waveman:
    image: docker.pkg.github.com/occloxium/wave-man/wave-man-server:2.8
    container_name: demo-wave-man
    restart: on-failure
    environment: 
      MONGO_INITDB_DATABASE: demo
    networks:
    - backend
    ports:
    - "5000:5000"

  db:
    image: mongo:4.2.5
    container_name: demo-mongodb
    restart: on-failure
    volumes:
    - db-data:/data/db
    environment: 
      MONGO_INITDB_DATABASE: demo
    networks:
    - backend
    ports:
    - "27017:27017"

networks:
  frontend:
  backend:

volumes:
  db-data: