version: "3"

services:
  client:
    image: node:latest
    container_name: demo-client
    restart: on-failure
    networks: 
    - frontend
    - backend
    volumes: 
    - ../client:/app
    working_dir: /app
    command: [ "npm", "run", "serve" ]
    ports: 
    - "8081:8080"

  api:
    image: node:alpine
    container_name: demo-api
    restart: on-failure
    depends_on: 
    - db
    environment: 
      PORT: "8080"
      MONGOURL: mongodb://demo-mongodb:27017
      WAVE_ENDPOINT: 'http://demo-wave-man:5000/wavify'
      API_ENDPOINT: 'http://demo-api:8080/api/v1/demo'
      DB: demo
      TOKEN: demotoken
    networks:
    - backend
    - frontend
    volumes: 
    - ../api:/app
    working_dir: /app
    command: [ "npm", "start" ]
    ports: 
    - "8080:8080"

  watchdog:
    # build: ../watchdog
    image: node:alpine
    container_name: demo-watchdog
    restart: on-failure
    environment: 
      VOLUME: /app/files
      PUBLIC_PATH: '{"prefix": "https", "hostname": "files.zoomoid.de", "dir": ""}'
      TOKEN: demotoken
      API_ENDPOINT: 'http://demo-api:8080/api/v1/demo'
    volumes:
    - ./files:/app/files
    - ../watchdog:/app
    working_dir: /app
    command: [ "npm", "start" ]
    networks:
    - backend
    ports:
    - "8082:8080"

  waveman:
    image: docker.pkg.github.com/occloxium/wave-man/wave-man:2.19.3
    container_name: demo-wave-man
    restart: on-failure
    environment: 
      MONGO_INITDB_DATABASE: demo
    networks:
    - backend
    volumes: 
    - ../../../web/wave-man/defaults:/app/config
    ports:
    - "8083:8080"

  db:
    image: mongo:4.2.5
    container_name: demo-mongodb
    restart: on-failure
    volumes:
    - db-data:/data/db
    environment: 
      MONGO_INITDB_DATABASE: demo
    networks:
    - backend
    ports:
    - "27017:27017"

networks:
  frontend:
  backend:

volumes:
  db-data: